$._ext_BTNDARK = {
    run: function () {
try {
var idsetd = charIDToTypeID("setd");
var desc2 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref1 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idfsel = charIDToTypeID("fsel");
ref1.putProperty(idChnl, idfsel);
desc2.putReference(idnull, ref1);
var idT = charIDToTypeID("T   ");
var ref2 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref2.putName(idChnl, "Darks-3");
desc2.putReference(idT, ref2);
executeAction(idsetd, desc2, DialogModes.NO);
} catch (e) {
try {
function darker() {
try {
var idDlt = charIDToTypeID("Dlt ");
var desc11 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref8 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref8.putName(idChnl, "New Selection");
desc11.putReference(idnull, ref8);
executeAction(idDlt, desc11, DialogModes.NO);
} catch (e) {}
try {
var idslct = charIDToTypeID("slct");
var desc3 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref2 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idChnl = charIDToTypeID("Chnl");
var idRGB = charIDToTypeID("RGB ");
ref2.putEnumerated(idChnl, idChnl, idRGB);
desc3.putReference(idnull, ref2);
executeAction(idslct, desc3, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc4 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref3 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idfsel = charIDToTypeID("fsel");
ref3.putProperty(idChnl, idfsel);
desc4.putReference(idnull, ref3);
var idT = charIDToTypeID("T   ");
var idOrdn = charIDToTypeID("Ordn");
var idNone = charIDToTypeID("None");
desc4.putEnumerated(idT, idOrdn, idNone);
executeAction(idsetd, desc4, DialogModes.NO);
var idMk = charIDToTypeID("Mk  ");
var desc5 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref3 = new ActionReference();
var idAdjL = charIDToTypeID("AdjL");
ref3.putClass(idAdjL);
desc5.putReference(idnull, ref3);
var idUsng = charIDToTypeID("Usng");
var desc6 = new ActionDescriptor();
var idNm = charIDToTypeID("Nm  ");
desc6.putString(idNm, "TK selection creation");
var idType = charIDToTypeID("Type");
var desc7 = new ActionDescriptor();
var idpresetKind = stringIDToTypeID("presetKind");
var idpresetKindType = stringIDToTypeID("presetKindType");
var idpresetKindDefault = stringIDToTypeID("presetKindDefault");
desc7.putEnumerated(idpresetKind, idpresetKindType, idpresetKindDefault);
var idLvls = charIDToTypeID("Lvls");
desc6.putObject(idType, idLvls, desc7);
var idAdjL = charIDToTypeID("AdjL");
desc5.putObject(idUsng, idAdjL, desc6);
executeAction(idMk, desc5, DialogModes.NO);
var idMk = charIDToTypeID("Mk  ");
var desc8 = new ActionDescriptor();
var idNw = charIDToTypeID("Nw  ");
var idChnl = charIDToTypeID("Chnl");
desc8.putClass(idNw, idChnl);
var idUsng = charIDToTypeID("Usng");
var desc9 = new ActionDescriptor();
var idT = charIDToTypeID("T   ");
var ref5 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idChnl = charIDToTypeID("Chnl");
var idGry = charIDToTypeID("Gry ");
ref5.putEnumerated(idChnl, idChnl, idGry);
var idLyr = charIDToTypeID("Lyr ");
var idOrdn = charIDToTypeID("Ordn");
var idMrgd = charIDToTypeID("Mrgd");
ref5.putEnumerated(idLyr, idOrdn, idMrgd);
desc9.putReference(idT, ref5);
var idInvr = charIDToTypeID("Invr");
desc9.putBoolean(idInvr, true);
var idClcl = charIDToTypeID("Clcl");
var idClcn = charIDToTypeID("Clcn");
var idMltp = charIDToTypeID("Mltp");
desc9.putEnumerated(idClcl, idClcn, idMltp);
var idSrctwo = charIDToTypeID("Src2");
var ref6 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idChnl = charIDToTypeID("Chnl");
var idGry = charIDToTypeID("Gry ");
ref6.putEnumerated(idChnl, idChnl, idGry);
var idLyr = charIDToTypeID("Lyr ");
var idOrdn = charIDToTypeID("Ordn");
var idMrgd = charIDToTypeID("Mrgd");
ref6.putEnumerated(idLyr, idOrdn, idMrgd);
desc9.putReference(idSrctwo, ref6);
var idInvS = charIDToTypeID("InvS");
desc9.putBoolean(idInvS, true);
var idClcl = charIDToTypeID("Clcl");
desc8.putObject(idUsng, idClcl, desc9);
executeAction(idMk, desc8, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc10 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref7 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref7.putEnumerated(idChnl, idOrdn, idTrgt);
desc10.putReference(idnull, ref7);
var idT = charIDToTypeID("T   ");
var desc11 = new ActionDescriptor();
var idNm = charIDToTypeID("Nm  ");
desc11.putString(idNm, "Darks-2");
var idChnl = charIDToTypeID("Chnl");
desc10.putObject(idT, idChnl, desc11);
executeAction(idsetd, desc10, DialogModes.NO);
var idMk = charIDToTypeID("Mk  ");
var desc12 = new ActionDescriptor();
var idNw = charIDToTypeID("Nw  ");
var idChnl = charIDToTypeID("Chnl");
desc12.putClass(idNw, idChnl);
var idUsng = charIDToTypeID("Usng");
var desc13 = new ActionDescriptor();
var idT = charIDToTypeID("T   ");
var ref8 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref8.putEnumerated(idChnl, idOrdn, idTrgt);
desc13.putReference(idT, ref8);
var idClcl = charIDToTypeID("Clcl");
var idClcn = charIDToTypeID("Clcn");
var idMltp = charIDToTypeID("Mltp");
desc13.putEnumerated(idClcl, idClcn, idMltp);
var idSrctwo = charIDToTypeID("Src2");
var ref9 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref9.putEnumerated(idChnl, idOrdn, idTrgt);
desc13.putReference(idSrctwo, ref9);
var idClcl = charIDToTypeID("Clcl");
desc12.putObject(idUsng, idClcl, desc13);
executeAction(idMk, desc12, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc14 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref10 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idfsel = charIDToTypeID("fsel");
ref10.putProperty(idChnl, idfsel);
desc14.putReference(idnull, ref10);
var idT = charIDToTypeID("T   ");
var ref11 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref11.putEnumerated(idChnl, idOrdn, idTrgt);
desc14.putReference(idT, ref11);
executeAction(idsetd, desc14, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc8 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref6 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref6.putEnumerated(idChnl, idOrdn, idTrgt);
desc8.putReference(idnull, ref6);
var idT = charIDToTypeID("T   ");
var desc9 = new ActionDescriptor();
var idNm = charIDToTypeID("Nm  ");
desc9.putString(idNm, "New Selection");
var idChnl = charIDToTypeID("Chnl");
desc8.putObject(idT, idChnl, desc9);
executeAction(idsetd, desc8, DialogModes.NO);
var idDlt = charIDToTypeID("Dlt ");
var desc16 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref13 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref13.putName(idChnl, "Darks-2");
desc16.putReference(idnull, ref13);
executeAction(idDlt, desc16, DialogModes.NO);
var idDlt = charIDToTypeID("Dlt ");
var desc17 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref14 = new ActionReference();
var idLyr = charIDToTypeID("Lyr ");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref14.putEnumerated(idLyr, idOrdn, idTrgt);
desc17.putReference(idnull, ref14);
executeAction(idDlt, desc17, DialogModes.NO);
var idslct = charIDToTypeID("slct");
var desc18 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref15 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idChnl = charIDToTypeID("Chnl");
var idRGB = charIDToTypeID("RGB ");
ref15.putEnumerated(idChnl, idChnl, idRGB);
desc18.putReference(idnull, ref15);
executeAction(idslct, desc18, DialogModes.NO);
} catch (e) {}
}
app.activeDocument.suspendHistory("Ch\u1ecdn v\u00f9ng t\u1ed1i", "darker()");
} catch (e) {}
}
app.bringToFront();

    }
};
