$._ext_BTNMID = {
    run: function () {
try {
function mid() {
try {
var idDlt = charIDToTypeID("Dlt ");
var desc11 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref8 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref8.putName(idChnl, "New Selection");
desc11.putReference(idnull, ref8);
executeAction(idDlt, desc11, DialogModes.NO);
} catch (e) {}
try {
var idslct = charIDToTypeID("slct");
var desc3 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref2 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idChnl = charIDToTypeID("Chnl");
var idRGB = charIDToTypeID("RGB ");
ref2.putEnumerated(idChnl, idChnl, idRGB);
desc3.putReference(idnull, ref2);
executeAction(idslct, desc3, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc4 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref3 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idfsel = charIDToTypeID("fsel");
ref3.putProperty(idChnl, idfsel);
desc4.putReference(idnull, ref3);
var idT = charIDToTypeID("T   ");
var idOrdn = charIDToTypeID("Ordn");
var idNone = charIDToTypeID("None");
desc4.putEnumerated(idT, idOrdn, idNone);
executeAction(idsetd, desc4, DialogModes.NO);
var idMk = charIDToTypeID("Mk  ");
var desc5 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref3 = new ActionReference();
var idAdjL = charIDToTypeID("AdjL");
ref3.putClass(idAdjL);
desc5.putReference(idnull, ref3);
var idUsng = charIDToTypeID("Usng");
var desc6 = new ActionDescriptor();
var idNm = charIDToTypeID("Nm  ");
desc6.putString(idNm, "TK selection creation");
var idType = charIDToTypeID("Type");
var desc7 = new ActionDescriptor();
var idpresetKind = stringIDToTypeID("presetKind");
var idpresetKindType = stringIDToTypeID("presetKindType");
var idpresetKindDefault = stringIDToTypeID("presetKindDefault");
desc7.putEnumerated(idpresetKind, idpresetKindType, idpresetKindDefault);
var idLvls = charIDToTypeID("Lvls");
desc6.putObject(idType, idLvls, desc7);
var idAdjL = charIDToTypeID("AdjL");
desc5.putObject(idUsng, idAdjL, desc6);
executeAction(idMk, desc5, DialogModes.NO);
var idMk = charIDToTypeID("Mk  ");
var desc8 = new ActionDescriptor();
var idNw = charIDToTypeID("Nw  ");
var idChnl = charIDToTypeID("Chnl");
desc8.putClass(idNw, idChnl);
var idUsng = charIDToTypeID("Usng");
var desc9 = new ActionDescriptor();
var idT = charIDToTypeID("T   ");
var ref5 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idChnl = charIDToTypeID("Chnl");
var idGry = charIDToTypeID("Gry ");
ref5.putEnumerated(idChnl, idChnl, idGry);
var idLyr = charIDToTypeID("Lyr ");
var idOrdn = charIDToTypeID("Ordn");
var idMrgd = charIDToTypeID("Mrgd");
ref5.putEnumerated(idLyr, idOrdn, idMrgd);
desc9.putReference(idT, ref5);
var idSrctwo = charIDToTypeID("Src2");
var ref6 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idChnl = charIDToTypeID("Chnl");
var idGry = charIDToTypeID("Gry ");
ref6.putEnumerated(idChnl, idChnl, idGry);
var idLyr = charIDToTypeID("Lyr ");
var idOrdn = charIDToTypeID("Ordn");
var idMrgd = charIDToTypeID("Mrgd");
ref6.putEnumerated(idLyr, idOrdn, idMrgd);
desc9.putReference(idSrctwo, ref6);
var idClcl = charIDToTypeID("Clcl");
desc8.putObject(idUsng, idClcl, desc9);
executeAction(idMk, desc8, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc10 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref7 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref7.putEnumerated(idChnl, idOrdn, idTrgt);
desc10.putReference(idnull, ref7);
var idT = charIDToTypeID("T   ");
var desc11 = new ActionDescriptor();
var idNm = charIDToTypeID("Nm  ");
desc11.putString(idNm, "Lights-1 temp");
var idChnl = charIDToTypeID("Chnl");
desc10.putObject(idT, idChnl, desc11);
executeAction(idsetd, desc10, DialogModes.NO);
var idMk = charIDToTypeID("Mk  ");
var desc12 = new ActionDescriptor();
var idNw = charIDToTypeID("Nw  ");
var idChnl = charIDToTypeID("Chnl");
desc12.putClass(idNw, idChnl);
var idUsng = charIDToTypeID("Usng");
var desc13 = new ActionDescriptor();
var idT = charIDToTypeID("T   ");
var ref8 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref8.putEnumerated(idChnl, idOrdn, idTrgt);
desc13.putReference(idT, ref8);
var idClcl = charIDToTypeID("Clcl");
var idClcn = charIDToTypeID("Clcn");
var idMltp = charIDToTypeID("Mltp");
desc13.putEnumerated(idClcl, idClcn, idMltp);
var idSrctwo = charIDToTypeID("Src2");
var ref9 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref9.putEnumerated(idChnl, idOrdn, idTrgt);
desc13.putReference(idSrctwo, ref9);
var idClcl = charIDToTypeID("Clcl");
desc12.putObject(idUsng, idClcl, desc13);
executeAction(idMk, desc12, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc14 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref10 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref10.putEnumerated(idChnl, idOrdn, idTrgt);
desc14.putReference(idnull, ref10);
var idT = charIDToTypeID("T   ");
var desc15 = new ActionDescriptor();
var idNm = charIDToTypeID("Nm  ");
desc15.putString(idNm, "Lights-2 temp");
var idChnl = charIDToTypeID("Chnl");
desc14.putObject(idT, idChnl, desc15);
executeAction(idsetd, desc14, DialogModes.NO);
var idMk = charIDToTypeID("Mk  ");
var desc16 = new ActionDescriptor();
var idNw = charIDToTypeID("Nw  ");
var idChnl = charIDToTypeID("Chnl");
desc16.putClass(idNw, idChnl);
var idUsng = charIDToTypeID("Usng");
var desc17 = new ActionDescriptor();
var idT = charIDToTypeID("T   ");
var ref11 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref11.putEnumerated(idChnl, idOrdn, idTrgt);
desc17.putReference(idT, ref11);
var idClcl = charIDToTypeID("Clcl");
var idClcn = charIDToTypeID("Clcn");
var idMltp = charIDToTypeID("Mltp");
desc17.putEnumerated(idClcl, idClcn, idMltp);
var idSrctwo = charIDToTypeID("Src2");
var ref12 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref12.putEnumerated(idChnl, idOrdn, idTrgt);
desc17.putReference(idSrctwo, ref12);
var idClcl = charIDToTypeID("Clcl");
desc16.putObject(idUsng, idClcl, desc17);
executeAction(idMk, desc16, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc18 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref13 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref13.putEnumerated(idChnl, idOrdn, idTrgt);
desc18.putReference(idnull, ref13);
var idT = charIDToTypeID("T   ");
var desc19 = new ActionDescriptor();
var idNm = charIDToTypeID("Nm  ");
desc19.putString(idNm, "Lights-3 temp");
var idChnl = charIDToTypeID("Chnl");
desc18.putObject(idT, idChnl, desc19);
executeAction(idsetd, desc18, DialogModes.NO);
var idDlt = charIDToTypeID("Dlt ");
var desc36 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref28 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref28.putName(idChnl, "Lights-2 temp");
desc36.putReference(idnull, ref28);
executeAction(idDlt, desc36, DialogModes.NO);
var idMk = charIDToTypeID("Mk  ");
var desc20 = new ActionDescriptor();
var idNw = charIDToTypeID("Nw  ");
var idChnl = charIDToTypeID("Chnl");
desc20.putClass(idNw, idChnl);
var idUsng = charIDToTypeID("Usng");
var desc21 = new ActionDescriptor();
var idT = charIDToTypeID("T   ");
var ref14 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref14.putName(idChnl, "Lights-1 temp");
desc21.putReference(idT, ref14);
var idInvr = charIDToTypeID("Invr");
desc21.putBoolean(idInvr, true);
var idClcl = charIDToTypeID("Clcl");
var idClcn = charIDToTypeID("Clcn");
var idMltp = charIDToTypeID("Mltp");
desc21.putEnumerated(idClcl, idClcn, idMltp);
var idSrctwo = charIDToTypeID("Src2");
var ref15 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref15.putName(idChnl, "Lights-1 temp");
desc21.putReference(idSrctwo, ref15);
var idInvS = charIDToTypeID("InvS");
desc21.putBoolean(idInvS, true);
var idClcl = charIDToTypeID("Clcl");
desc20.putObject(idUsng, idClcl, desc21);
executeAction(idMk, desc20, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc22 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref16 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref16.putEnumerated(idChnl, idOrdn, idTrgt);
desc22.putReference(idnull, ref16);
var idT = charIDToTypeID("T   ");
var desc23 = new ActionDescriptor();
var idNm = charIDToTypeID("Nm  ");
desc23.putString(idNm, "Darks-2 temp");
var idChnl = charIDToTypeID("Chnl");
desc22.putObject(idT, idChnl, desc23);
executeAction(idsetd, desc22, DialogModes.NO);
var idDlt = charIDToTypeID("Dlt ");
var desc37 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref29 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref29.putName(idChnl, "Lights-1 temp");
desc37.putReference(idnull, ref29);
executeAction(idDlt, desc37, DialogModes.NO);
var idMk = charIDToTypeID("Mk  ");
var desc24 = new ActionDescriptor();
var idNw = charIDToTypeID("Nw  ");
var idChnl = charIDToTypeID("Chnl");
desc24.putClass(idNw, idChnl);
var idUsng = charIDToTypeID("Usng");
var desc25 = new ActionDescriptor();
var idT = charIDToTypeID("T   ");
var ref17 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref17.putEnumerated(idChnl, idOrdn, idTrgt);
desc25.putReference(idT, ref17);
var idClcl = charIDToTypeID("Clcl");
var idClcn = charIDToTypeID("Clcn");
var idMltp = charIDToTypeID("Mltp");
desc25.putEnumerated(idClcl, idClcn, idMltp);
var idSrctwo = charIDToTypeID("Src2");
var ref18 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref18.putEnumerated(idChnl, idOrdn, idTrgt);
desc25.putReference(idSrctwo, ref18);
var idClcl = charIDToTypeID("Clcl");
desc24.putObject(idUsng, idClcl, desc25);
executeAction(idMk, desc24, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc26 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref19 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref19.putEnumerated(idChnl, idOrdn, idTrgt);
desc26.putReference(idnull, ref19);
var idT = charIDToTypeID("T   ");
var desc27 = new ActionDescriptor();
var idNm = charIDToTypeID("Nm  ");
desc27.putString(idNm, "Darks-3 temp");
var idChnl = charIDToTypeID("Chnl");
desc26.putObject(idT, idChnl, desc27);
executeAction(idsetd, desc26, DialogModes.NO);
var idDlt = charIDToTypeID("Dlt ");
var desc34 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref26 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref26.putName(idChnl, "Darks-2 temp");
desc34.putReference(idnull, ref26);
executeAction(idDlt, desc34, DialogModes.NO);
var idMk = charIDToTypeID("Mk  ");
var desc28 = new ActionDescriptor();
var idNw = charIDToTypeID("Nw  ");
var idChnl = charIDToTypeID("Chnl");
desc28.putClass(idNw, idChnl);
var idUsng = charIDToTypeID("Usng");
var desc29 = new ActionDescriptor();
var idT = charIDToTypeID("T   ");
var ref20 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref20.putEnumerated(idChnl, idOrdn, idTrgt);
desc29.putReference(idT, ref20);
var idInvr = charIDToTypeID("Invr");
desc29.putBoolean(idInvr, true);
var idClcl = charIDToTypeID("Clcl");
var idClcn = charIDToTypeID("Clcn");
var idMltp = charIDToTypeID("Mltp");
desc29.putEnumerated(idClcl, idClcn, idMltp);
var idSrctwo = charIDToTypeID("Src2");
var ref21 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref21.putName(idChnl, "Lights-3 temp");
desc29.putReference(idSrctwo, ref21);
var idInvS = charIDToTypeID("InvS");
desc29.putBoolean(idInvS, true);
var idClcl = charIDToTypeID("Clcl");
desc28.putObject(idUsng, idClcl, desc29);
executeAction(idMk, desc28, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc30 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref22 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idfsel = charIDToTypeID("fsel");
ref22.putProperty(idChnl, idfsel);
desc30.putReference(idnull, ref22);
var idT = charIDToTypeID("T   ");
var ref23 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref23.putEnumerated(idChnl, idOrdn, idTrgt);
desc30.putReference(idT, ref23);
executeAction(idsetd, desc30, DialogModes.NO);
var idsetd = charIDToTypeID("setd");
var desc31 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref24 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref24.putEnumerated(idChnl, idOrdn, idTrgt);
desc31.putReference(idnull, ref24);
var idT = charIDToTypeID("T   ");
var desc32 = new ActionDescriptor();
var idNm = charIDToTypeID("Nm  ");
desc32.putString(idNm, "New Selection");
var idChnl = charIDToTypeID("Chnl");
desc31.putObject(idT, idChnl, desc32);
executeAction(idsetd, desc31, DialogModes.NO);
var idDlt = charIDToTypeID("Dlt ");
var desc33 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref25 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref25.putName(idChnl, "Darks-3 temp");
desc33.putReference(idnull, ref25);
executeAction(idDlt, desc33, DialogModes.NO);
var idDlt = charIDToTypeID("Dlt ");
var desc35 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref27 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
ref27.putName(idChnl, "Lights-3 temp");
desc35.putReference(idnull, ref27);
executeAction(idDlt, desc35, DialogModes.NO);
var idDlt = charIDToTypeID("Dlt ");
var desc38 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref30 = new ActionReference();
var idLyr = charIDToTypeID("Lyr ");
var idOrdn = charIDToTypeID("Ordn");
var idTrgt = charIDToTypeID("Trgt");
ref30.putEnumerated(idLyr, idOrdn, idTrgt);
desc38.putReference(idnull, ref30);
executeAction(idDlt, desc38, DialogModes.NO);
var idslct = charIDToTypeID("slct");
var desc39 = new ActionDescriptor();
var idnull = charIDToTypeID("null");
var ref31 = new ActionReference();
var idChnl = charIDToTypeID("Chnl");
var idChnl = charIDToTypeID("Chnl");
var idRGB = charIDToTypeID("RGB ");
ref31.putEnumerated(idChnl, idChnl, idRGB);
desc39.putReference(idnull, ref31);
executeAction(idslct, desc39, DialogModes.NO);
} catch (e) {}
}
app.activeDocument.suspendHistory("Ch\u1ecdn t\u00f4ng trung gian", "mid()");
} catch (e) {}
app.bringToFront();

    }
};
